class AppState:
    """
    Holds global, mutable application state for the entire app.
    The GUI, controller, and AI updater all read/write this object.
    """

    def __init__(self):
        # --------------------------------------------
        # User–selected input files
        # --------------------------------------------
        self.dump_path: str | None = None          # Path to new dump.cs / ida dump
        self.source_path: str | None = None        # Path to main.cpp

        # --------------------------------------------
        # Parsed / processed data
        # --------------------------------------------
        self.parsed_dump: dict = {}                # { "Class.Method": new_offset }
        self.parsed_source: dict = {}              # { "Class.Method": old_offset }
        self.analysis_results: dict = {}           # { "Class.Method": {old, new, status} }

        # --------------------------------------------
        # AI related data
        # --------------------------------------------
        self.ai_generated_cpp: str | None = None   # Full updated main.cpp generated by AI
        self.ai_raw_response: str | None = None    # Unprocessed AI response for debugging
        self.ai_enabled: bool = True               # Toggle AI usage
        self.last_prompt: str | None = None        # Last AI prompt for logging

        # --------------------------------------------
        # UI settings
        # --------------------------------------------
        self.dark_theme_enabled: bool = True

    # --------------------------------------------
    # Reset everything
    # --------------------------------------------
    def reset(self):
        """Clear all stored application state."""
        self.dump_path = None
        self.source_path = None

        self.parsed_dump.clear()
        self.parsed_source.clear()
        self.analysis_results.clear()

        # Reset AI state
        self.ai_generated_cpp = None
        self.ai_raw_response = None
        self.last_prompt = None

        # Leave theme unchanged
